In [15]:
from tensorflow import keras

In [16]:
from keras.preprocessing.text import one_hot

In [17]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
vocab_size=10000

In [20]:
#One hot representation
one_hot = [one_hot(words,vocab_size) for words in sent]
print(one_hot)

[[7813, 1466, 4413, 1314], [7813, 1466, 4413, 3183], [7813, 3891, 4413, 9639], [7247, 2488, 9279, 2526, 2953], [7247, 2488, 9279, 2526, 4432], [1612, 7813, 8925, 4413, 3897], [2124, 9474, 4713, 2526]]


In [26]:
# Word Embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
import numpy as np

In [30]:
sent_length=8
embedded_docs = pad_sequences(one_hot,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7813 1466 4413 1314]
 [   0    0    0    0 7813 1466 4413 3183]
 [   0    0    0    0 7813 3891 4413 9639]
 [   0    0    0 7247 2488 9279 2526 2953]
 [   0    0    0 7247 2488 9279 2526 4432]
 [   0    0    0 1612 7813 8925 4413 3897]
 [   0    0    0    0 2124 9474 4713 2526]]


In [32]:
dim = 10

In [33]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [35]:
print(model.predict(embedded_docs))

[[[ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [-0.01997368 -0.00520924  0.03219214 -0.00749389  0.02802792
    0.03371571 -0.02199762 -0.02020501  0.03853538 -0.03120884]
  [ 0.04736985  0.01794486 -0.04626466 -0.02639395  0.04490698
    0.04512116 -0.00566325  0.00922046  0.02888808  0.00620016]
  [ 0.02537817  0.04378033  0.02838511 -0.04117551 -0.01692462
    0.043242    0.0495101   0.02528195  0.02704909 -0.04245633]
  [ 0.02340163  0.01824996 -0.02157582  0.01216657  0.02858127
   -0.03043965  0.02758838 -0.03195523  0.001038

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 7813, 1466, 4413, 1314])

In [38]:
print(model.predict(embedded_docs))[0]

[[[ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [ 0.03270869  0.00990034  0.0137175   0.00187546 -0.02336555
    0.01679926 -0.04685484 -0.01610476 -0.0086394   0.02860475]
  [-0.01997368 -0.00520924  0.03219214 -0.00749389  0.02802792
    0.03371571 -0.02199762 -0.02020501  0.03853538 -0.03120884]
  [ 0.04736985  0.01794486 -0.04626466 -0.02639395  0.04490698
    0.04512116 -0.00566325  0.00922046  0.02888808  0.00620016]
  [ 0.02537817  0.04378033  0.02838511 -0.04117551 -0.01692462
    0.043242    0.0495101   0.02528195  0.02704909 -0.04245633]
  [ 0.02340163  0.01824996 -0.02157582  0.01216657  0.02858127
   -0.03043965  0.02758838 -0.03195523  0.001038

TypeError: 'NoneType' object is not subscriptable